sonar.projectKey=CineTrack-Social-Graph-Activity-Feed_socialgraphactivityfeed
sonar.organization=cinetrack-social-graph-activity-feed

sonar.sources=Backend/servidor,Frontend/front-cinetrack/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/.output/**,**/build/**
sonar.sourceEncoding=UTF-8
