# Docker Compose para desarrollo local
# Incluye RabbitMQ y MongoDB para testing rápido

version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: socialgraph_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: socialgraph
    volumes:
      - mongodb_data:/data/db
    networks:
      - consumer_network

  # RabbitMQ con Management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: socialgraph_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # Puerto AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - consumer_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  consumer_network:
    driver: bridge
